#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('LaravelRUS Skeleton Installer', '1.0.3');
$app->add(new LaravelRUS\Installer\Console\NewCommand);
$app->add(new LaravelRUS\Installer\Console\TypesCommand);
$app->run();
